# Generated by Django 6.0.4 on 2026-04-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_athlete_eventregistration_rosterentry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medaltally',
            options={'ordering': ['-gold', '-silver', '-bronze', 'department__name'], 'verbose_name_plural': 'Medal Tallies'},
        ),
    ]
