# Generated by Django 6.0.4 on 2026-04-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_medaltally_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medaltally',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='podiumresult',
            name='points_awarded',
        ),
    ]
