# Generated by Django 6.0.4 on 2026-04-27 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        ('tournaments', '0004_remove_medaltally_total_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryoutApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('school_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('program_course', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=20)),
                ('prior_experience', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=12)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('selected', 'Selected'), ('not_selected', 'Not Selected'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_athlete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_tryout_application', to='tournaments.athlete')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryout_applications', to='core.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tryout_applications', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryout_applications', to='tournaments.eventschedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school_email', 'schedule')},
            },
        ),
    ]
