# Generated by Django 6.0.4 on 2026-04-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        ('tournaments', '0005_tryoutapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryoutapplication',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tryoutapplication',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tryoutapplication',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('student_number', models.CharField(max_length=50)),
                ('code_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryout_email_codes', to='core.department')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryout_email_codes', to='tournaments.eventschedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'student_number', 'department', 'schedule'], name='tournaments_email_0f58ad_idx'), models.Index(fields=['created_at'], name='tournaments_created_38c819_idx')],
            },
        ),
    ]
