# Generated by Django 6.0.4 on 2026-04-27 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsarticle'),
        ('events', '0001_initial'),
        ('rooney', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('event_completion', 'Event Completion'), ('medal_update', 'Medal Update'), ('schedule_highlight', 'Schedule Highlight'), ('rooney_summary', 'Rooney Summary'), ('manual', 'Manual')], default='manual', max_length=30)),
                ('scope_type', models.CharField(choices=[('match_result', 'Match Result'), ('podium_schedule', 'Podium Schedule'), ('event', 'Event'), ('leaderboard', 'Leaderboard'), ('manual', 'Manual')], default='manual', max_length=30)),
                ('scope_key', models.CharField(max_length=255)),
                ('input_snapshot_json', models.JSONField(default=dict)),
                ('generated_title', models.CharField(max_length=255)),
                ('generated_summary', models.TextField()),
                ('generated_body', models.TextField()),
                ('model_name', models.CharField(default='template-grounded-v1', max_length=120)),
                ('prompt_version', models.CharField(default='recap_v1', max_length=50)),
                ('citation_map_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('discarded', 'Discarded'), ('published', 'Published')], default='generated', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recaps', to='core.department')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recaps', to='events.event')),
                ('linked_news_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_ai_recaps', to='core.newsarticle')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_recaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-updated_at'],
                'unique_together': {('scope_type', 'scope_key')},
            },
        ),
    ]
